name: Build Android and iOS
on: push
jobs:
  install_and_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run Linter
        run: |
          npm run lint
